name:                hencode
version:             0.2.0.0
github:              "thunklife/hencode"
license:             BSD3
author:              "thunklife"
maintainer:          "thunklife@fastmail.fm"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hencode#readme>

dependencies:
- base >= 4.7 && < 5
- base64-bytestring
- bytestring
- turtle
- text

library:
  source-dirs: src

executables:
  hencode:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hencode

tests:
  hencode-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hencode
